name: Test Hexo Site with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18'
      HEXO_PORT: 4000
      PLAYWRIGHT_REPO: 'https://github.com/dhanesh-kh/playwright.git'
      PLAYWRIGHT_CONFIG: './playwright.config.js'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Hexo and install dependencies
        run: |
          npm install -g hexo-cli
          npm install
          npx playwright install-deps
          npx playwright install

      - name: Generate site and start Hexo server
        run: |
          hexo generate
          npx serve -s public -l $HEXO_PORT &

      - name: Wait for Hexo server
        run: sleep 3

      - name: Clone Playwright repository, install dependencies, and run tests
        run: |
          git clone $PLAYWRIGHT_REPO
          cd playwright
          npm install
          npx playwright install
          npx playwright test --config=$PLAYWRIGHT_CONFIG

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      - name: Set up Hexo and install dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate Hexo site
        run: |
          hexo generate

      - name: Add .nojekyll file
        run: touch ./public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
