name: Test Hexo Site with Playwright

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing the Hexo site
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      # Set up Node.js (version 18 as required by Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Hexo CLI and dependencies
      - name: Install Hexo and dependencies
        run: |
          cd ./readme
          npm install hexo-cli -g
          npm install

      # Generate the Hexo static site
      - name: Generate Hexo site
        run: |
          hexo generate

      # Install and start a simple HTTP server to serve the generated Hexo site
      - name: Start HTTP server to serve Hexo site
        run: |
          npm install -g http-server
          http-server ./public -p 4000 &

      # Wait for the HTTP server to start
      - name: Wait for the HTTP server to start
        run: sleep 10  # Adjusted wait time for server start

      # Clone the Playwright test repository (if different)
      - name: Clone Playwright test repository
        run: |
          git clone https://github.com/dhanesh-kh/playwright.git  # Replace with actual Playwright test repo if needed
          cd playwright
          npm install

      # Install Playwright browsers and dependencies
      - name: Install Playwright and browsers
        run: |
          npm install @playwright/test
          npx playwright install

      # Run Playwright tests against the generated Hexo site
      - name: Run Playwright tests
        run: |
          cd playwright
          npx playwright test --config=./playwright.config.js

      # Display test artifacts in case of failure
      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: test-results/
