name: Test Hexo Site with Playwright

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing the Hexo site
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      # Set up Node.js (version 18 as required by Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Hexo CLI and dependencies
      - name: Install Hexo and dependencies
        run: |
          cd ./readme
          npm install hexo-cli -g
          npm install

      # Generate the Hexo static site
      - name: Generate Hexo site
        run: |
          hexo generate
          
      # Install dependencies required to run Playwright browsers on the system
      - name: Install Playwright dependencies
        run: |
          npx playwright install-deps

      # Start the Hexo server to serve the generated site
      - name: Start Hexo server
        run: |
          cd ./readme
          hexo server -p 4000 &

      # Wait for the Hexo server to start
      - name: Wait for the Hexo server to start
        run: sleep 3  # Adjusted wait time for server start

      # Check if the Hexo server is up and running
      - name: Check if Hexo server is up
        run: |
          curl --fail http://localhost:4000 || exit 1

      # Clone the Playwright test repository (if different)
      - name: Clone Playwright test repository
        run: |
          git clone https://github.com/dhanesh-kh/playwright.git  # Replace with actual Playwright test repo if needed
          cd playwright
          npm install

      # Install Playwright browsers and dependencies
      - name: Install Playwright and browsers
        run: |
          npm install @playwright/test
          npx playwright install

      # Run Playwright tests against the generated Hexo site
      - name: Run Playwright tests
        run: |
          cd playwright
          npx playwright test --config=./playwright.config.js

