name: Test Hexo Site with Playwright

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18'
      HEXO_PORT: 4000
      PLAYWRIGHT_REPO: 'https://github.com/dhanesh-kh/playwright.git'
      PLAYWRIGHT_CONFIG: './playwright.config.js'

    steps:
      # Checkout the repository containing the Hexo site
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js, install Hexo and Playwright dependencies
      - name: Set up environment and install dependencies
        run: |
          npm install -g hexo-cli
          cd ./readme
          npm install

          npx playwright install-deps
          npx playwright install

      # Generate the site and start the Hexo server
      - name: Generate site and start Hexo server
        run: |
          cd ./readme
          hexo generate
          hexo server -p $HEXO_PORT &

      # Wait for the Hexo server to start
      - name: Wait for Hexo server
        run: sleep 3

      # Clone Playwright repository, install dependencies, and run tests
      - name: Clone Playwright repository, install dependencies, and run tests
        run: |
          git clone $PLAYWRIGHT_REPO
          cd playwright
          npm install
          npx playwright test --config=$PLAYWRIGHT_CONFIG
