name: Test Hexo Site

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v3

      # Install Node.js (updated to v18)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to Node.js v18 as required by Playwright

      # Install Hexo CLI and dependencies
      - name: Install Hexo and dependencies
        run: |
          cd ./readme
          npm install hexo-cli -g
          npm install

      # Generate the static website
      - name: Generate Hexo site
        run: |
          hexo generate

      # Install and start a simple HTTP server to serve the generated site
      - name: Start HTTP server
        run: |
          npm install -g http-server
          http-server ./public -p 4000 &
          
      # Wait for the server to start
      - name: Wait for server to start
        run: sleep 5

      # Clone the Playwright test repository
      - name: Clone Playwright test repository
        run: |
          git clone https://github.com/dhanesh-kh/playwright.git
          cd playwright
          npm install

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: |
          npm init playwright@latest
          npx playwright install

      # Run the Playwright tests against the generated Hexo site
      - name: Run Playwright tests
        run: |
          cd playwright
          npx playwright test --config=./playwright.config.js
          
      # Optionally, you can add steps to deploy the Hexo site after testing
